server:
 port: 9296

spring:
 application:
  name: CONFIG-SERVER
 cloud:
  config:
   server:
    git:
     default-label: main
     uri: https://github.com/YashzAlphaGeek/Spring-Boot-Microservices
     clone-on-start: true 